export const AISTUDIOS_TOKEN_REQUESTED = 'AISTUDIOS_TOKEN_REQUESTED';
export const AISTUDIOS_TOKEN_SUCCEEDED = 'AISTUDIOS_TOKEN_SUCCEEDED';
export const AISTUDIOS_TOKEN_FAILED = 'AISTUDIOS_TOKEN_FAILED';
export const AISTUDIOS_MODELS_REQUESTED = 'AISTUDIOS_MODELS_REQUESTED';
export const AISTUDIOS_MODELS_SUCCEEDED = 'AISTUDIOS_MODELS_SUCCEEDED';
export const AISTUDIOS_MODELS_FAILED = 'AISTUDIOS_MODELS_FAILED';
export const AISTUDIOS_VIDEO_REQUESTED = 'AISTUDIOS_VIDEO_REQUESTED';
export const AISTUDIOS_VIDEO_SUCCEEDED = 'AISTUDIOS_VIDEO_SUCCEEDED';
export const AISTUDIOS_VIDEO_FAILED = 'AISTUDIOS_VIDEO_FAILED';
export const AISTUDIOS_PROJECT_REQUESTED = 'AISTUDIOS_PROJECT_REQUESTED';
export const AISTUDIOS_PROJECT_SUCCEEDED = 'AISTUDIOS_PROJECT_SUCCEEDED';
export const AISTUDIOS_PROJECT_FAILED = 'AISTUDIOS_PROJECT_FAILED';

export const TTV_SELECTED = 'TTV_SELECTED';
export const TTV_FETCH_REQUESTED = 'TTV_FETCH_REQUESTED';
export const TTV_FETCH_SUCCEEDED = 'TTV_FETCH_SUCCEEDED';
export const TTV_FETCH_FAILED = 'TTV_FETCH_FAILED';

export const TTV_ADD_REQUESTED = 'TTV_ADD_REQUESTED';
export const TTV_ADD_SUCCEEDED = 'TTV_ADD_SUCCEEDED';
export const TTV_ADD_FAILED = 'TTV_ADD_FAILED';

export const TTV_UPDATE_REQUESTED = 'TTV_UPDATE_REQUESTED';
export const TTV_UPDATE_SUCCEEDED = 'TTV_UPDATE_SUCCEEDED';
export const TTV_UPDATE_FAILED = 'TTV_UPDATE_FAILED';

export const TTV_DELETE_REQUESTED = 'TTV_DELETE_REQUESTED';
export const TTV_DELETE_SUCCEEDED = 'TTV_DELETE_SUCCEEDED';
export const TTV_DELETE_FAILED = 'TTV_DELETE_FAILED';
