export const TTV_SELECTED = "TTV_SELECTED";

export const TTV_FETCH_REQUESTED = "TTV_FETCH_REQUESTED";
export const TTV_FETCH_SUCCEEDED = "TTV_FETCH_SUCCEEDED";
export const TTV_FETCH_FAILED = "TTV_FETCH_FAILED";

export const TTV_ADD_REQUESTED = "TTV_ADD_REQUESTED";
export const TTV_ADD_SUCCEEDED = "TTV_ADD_SUCCEEDED";
export const TTV_ADD_FAILED = "TTV_ADD_FAILED";

export const TTV_UPDATE_REQUESTED = "TTV_UPDATE_REQUESTED";
export const TTV_UPDATE_SUCCEEDED = "TTV_UPDATE_SUCCEEDED";
export const TTV_UPDATE_FAILED = "TTV_UPDATE_FAILED";

export const TTV_DELETE_REQUESTED = "TTV_DELETE_REQUESTED";
export const TTV_DELETE_SUCCEEDED = "TTV_DELETE_SUCCEEDED";
export const TTV_DELETE_FAILED = "TTV_DELETE_FAILED";